### PR TITLE
remove -

### PR DESCRIPTION
**Pull request by TheQuackyDuck**
also remember to add stuff to it, (under the `token: ${{ secrets.METRICS_TOKEN }}` ).  https://github.com/lowlighter/metrics/blob/master/source/plugins/README.md

### CODE REVIEW

**Comment by TheQuackyDuck** [comment]
and did you add a repository secret called METRICS_TOKEN? I told you everything to do https://github.com/whippingdot/whippingdot/issues/4. This is what I said:

> Ok (assuming you saw it cuz you thumbs uped it). 

> I can help!

> ## First Part

> 1. Go to your profile settings: https://github.com/settings/profile

> 2. You should see a thing called "Developer settings" towards bottom of the left bar (?). Click it.

> 3. Click "Personal access tokens"

> 4. Click "Generate new token"

> 5. In the "note" box type readme (that's what i did), and for the scopes i just selected everything :/

> 6. Then click "Generate token"

> 7. Copy the token. (a bunch of letters and symbols and numbers)

> 8. Now head over to your profile readme, https://github.com/Time-dragon/Time-dragon

> 9. Now go to your **repository** settings

> 10. Click "Secrets" on the left bar

> 11. Click "New repository secret"

> 12. Name it whatever you want but if you want to follow along, name it `METRICS_TOKEN`

> 13. Paste the token you copied before

> 14. Click add secret.

> ## Second Part

> 15. (We're still on your profile readme repo okay?) https://github.com/Time-dragon/Time-dragon

> 16. Click "Add file", "Create new file", then in the "Name your file" box type `.github/workflows/main.yml`.

> 17. Copy paste this into the file content (or whatever you call it)

> ```
> name: Metrics
> on:
>   # Schedule updates (each hour)
>   schedule: [{cron: "0 * * * *"}]
>   # Lines below let you run workflow manually and on each commit (optional)
>   workflow_dispatch:
>   push: {branches: ["master", "main"]}
> jobs:
>   github-metrics:
>     runs-on: ubuntu-latest
>     steps:
>       # See action.yml for all options
>       - name: lowlighter/metrics 😁
>         uses: lowlighter/metrics@latest
>         with:
>           user: Time-dragon
>           token: ${{ secrets.METRICS_TOKEN }}
> ```

> ## Third Part

> Now this is the fun part!

> 20. Go to https://github.com/lowlighter/metrics

> 21. Now let's say I want to use the Recent stared repositories https://github.com/lowlighter/metrics/blob/master/source/plugins/stars/README.md

> 22. What I would do is under the

> ```
>         with:
>           user: Time-dragon
>           token: ${{ secrets.METRICS_TOKEN }}
> ```

> type the thing it says. In this case,

> ```
>     plugin_stars: yes
>     plugin_stars_limit: 4 # Limit to 4 entries
> ```

> 23. Tada! You can keep adding on and the thing after the # is a comment, so that can help you of what the thing means left to it.

> 24. When you feel satisfied with it, click "Start commit" :)

> 25. On the `README.md` file, type this: `GitHub Metrics` where you want the long metrics to be.

> 26. And yeah! It took me 30 minutes to write this so I hope you enjoy.

> 27. If you have any questions I'll be free to answer it (as long as I'm not busy).

> @Time-dragon

**Comment by Time-dragon** [comment]
> did you add a repository secret called METRICS_TOKEN?

Yes

**Comment by TheQuackyDuck** [comment]
ah yes, see, it works. But you can add more to the metrics @Time-dragon

**Comment by firefish111** [comment]
no u

**Comment by TheQuackyDuck** [comment]
:P

**Pull request merged**
